name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to publish'
        required: false

jobs:

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create release keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
        run: |
          echo "$RELEASE_KEYSTORE" > release.keystore.asc
          echo "$RELEASE_KEYSTORE_PASSPHRASE" | gpg -d --batch --passphrase-fd 0 release.keystore.asc > release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Assemble Artifact
        run: ./gradlew assembleFreeDynamic

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: apk
          path: lemuroid-app/build/outputs/apk/freeDynamic/release/lemuroid-app-free-dynamic-release.apk

  publish_apk:
    name: Publish APK on Github
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.1.0
        with:
          name: apk

      - name: Create pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Pre-release"
          files: lemuroid-app-free-dynamic-release.apk
